// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Boolean path parameter for toggle endpoints (e.g. `/respawn/true`).
 *
 * Replaces manual `match enabled_str { "true" => ..., "false" => ... }` parsing.
 * Axum deserializes the path segment automatically; ts-rs generates `"true" | "false"`.
 */
export type BoolParam = "true" | "false";
