// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason why a composable node is blocked
 */
export type ComposableBlockReason = "container_stopped" | "container_failed" | "container_not_started" | "shutdown";
