// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposableBlockReason } from "./ComposableBlockReason";

/**
 * Status for composable nodes (loaded into containers)
 */
export type ComposableNodeStatus = { "status": "loaded" } | { "status": "loading" } | { "status": "unloading" } | { "status": "failed" } | { "status": "pending" } | { "status": "unloaded" } | { "status": "blocked", "reason": ComposableBlockReason };
