// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Floating-point range constraint from ParameterDescriptor.
 */
export type FloatRange = { from: number, to: number, step: number, };
