// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health summary statistics for all members
 */
export type HealthSummary = { processes_running: number, processes_stopped: number, nodes_running: number, nodes_stopped: number, nodes_failed: number, nodes_total: number, containers_running: number, containers_stopped: number, containers_failed: number, containers_total: number, composable_loaded: number, composable_failed: number, composable_pending: number, composable_total: number, 
/**
 * Number of nodes with significant stderr output (>10KB)
 */
noisy: number, };
