// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Integer range constraint from ParameterDescriptor.
 */
export type IntegerRange = { from: bigint, to: bigint, step: bigint, };
