// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of node in the registry
 */
export type NodeType = "node" | "container" | "composable_node";
