// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node status for regular nodes and containers (process-based)
 */
export type NodeStatus = "running" | "stopped" | "failed" | "pending";
