// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeType } from "./NodeType";
import type { UnifiedStatus } from "./UnifiedStatus";

/**
 * Detailed information about a node (for API responses)
 */
export type NodeDetails = { cmdline?: string | null, 
/**
 * Canonical collision-proof member id (`kind:/ns/name[#N]`, phase-50).
 * THE key for API routes and frontend maps; `name` is display-only.
 */
id: string, name: string, node_type: NodeType, status: UnifiedStatus, pid: number | null, package: string | null, executable: string, namespace: string | null, target_container?: string | null, container_name?: string | null, 
/**
 * Canonical id of the resolved parent container (phase-50)
 */
container_id?: string | null, is_container: boolean, exec_name?: string | null, node_name?: string | null, 
/**
 * Worst diagnostic level attributed to this member (phase 62 W2).
 *
 * `None` means NO diagnostic was attributed — not that the member is
 * healthy. The UI must render those differently: a node nobody publishes
 * diagnostics for and a node publishing OK are different states, and
 * showing both green is the mistake this field exists to avoid.
 *
 * Derived from the registry's AGED view, so a member whose publishers
 * went silent badges stale rather than keeping its last green.
 */
diagnostic_level?: string | null, 
/**
 * Unix timestamp (seconds) when stderr was last modified
 */
stderr_last_modified?: number, 
/**
 * Size of stderr file in bytes
 */
stderr_size: number, 
/**
 * Last few lines of stderr for quick preview
 */
stderr_preview?: Array<string> | null, 
/**
 * Whether respawn is enabled for this node
 */
respawn_enabled?: boolean | null, 
/**
 * Respawn delay in seconds
 */
respawn_delay?: number | null, 
/**
 * Auto-load when container starts (for composable nodes)
 */
auto_load?: boolean | null, 
/**
 * Whether this composable node has its own log files (isolated mode)
 */
has_own_logs: boolean, };
