// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeType } from "./NodeType";
import type { UnifiedStatus } from "./UnifiedStatus";

/**
 * Detailed information about a node (for API responses)
 */
export type NodeDetails = { cmdline?: string | null, name: string, node_type: NodeType, status: UnifiedStatus, pid: number | null, package: string | null, executable: string, namespace: string | null, target_container?: string | null, container_name?: string | null, is_container: boolean, exec_name?: string | null, node_name?: string | null, 
/**
 * Unix timestamp (seconds) when stderr was last modified
 */
stderr_last_modified?: number, 
/**
 * Size of stderr file in bytes
 */
stderr_size: number, 
/**
 * Last few lines of stderr for quick preview
 */
stderr_preview?: Array<string> | null, 
/**
 * Whether respawn is enabled for this node
 */
respawn_enabled?: boolean | null, 
/**
 * Respawn delay in seconds
 */
respawn_delay?: number | null, 
/**
 * Auto-load when container starts (for composable nodes)
 */
auto_load?: boolean | null, };
