// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatRange } from "./FloatRange";
import type { IntegerRange } from "./IntegerRange";
import type { ParamValue } from "./ParamValue";

/**
 * Full parameter entry for the web UI.
 */
export type ParamEntry = { name: string, value: ParamValue, 
/**
 * Human-readable type name: "bool", "integer", "double", "string", etc.
 */
type_name: string, description: string, read_only: boolean, integer_range?: IntegerRange | null, floating_point_range?: FloatRange | null, };
