// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamValue } from "./ParamValue";

/**
 * A single parameter update for SSE events.
 */
export type ParamUpdate = { param_name: string, value: ParamValue, };
