// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-friendly parameter value enum (maps to ParameterType constants).
 *
 * Serde tagged representation allows the web UI to send/receive values like:
 *   `{ "type": "Double", "value": 3.14 }`
 *   `{ "type": "Bool", "value": true }`
 *   `{ "type": "NotSet" }`
 */
export type ParamValue = { "type": "Bool", "value": boolean } | { "type": "Integer", "value": bigint } | { "type": "Double", "value": number } | { "type": "String", "value": string } | { "type": "BoolArray", "value": Array<boolean> } | { "type": "IntegerArray", "value": Array<bigint> } | { "type": "DoubleArray", "value": Array<number> } | { "type": "StringArray", "value": Array<string> } | { "type": "ByteArray", "value": Array<number> } | { "type": "NotSet" };
