// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a set operation.
 */
export type SetParamResult = { successful: boolean, reason: string, };
