// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockReason } from "./BlockReason";

/**
 * State events emitted by actors
 *
 * These events are sent to the coordinator for:
 * - Web UI state updates
 * - Logging/metrics
 * - Coordination between actors
 */
export type StateEvent = { "type": "started", 
/**
 * Member name
 */
name: string, 
/**
 * Process ID
 */
pid: number, } | { "type": "exited", 
/**
 * Member name
 */
name: string, 
/**
 * Exit code (None if killed)
 */
exit_code: number | null, } | { "type": "respawning", 
/**
 * Member name
 */
name: string, 
/**
 * Current attempt number
 */
attempt: number, 
/**
 * Delay before spawn (seconds)
 */
delay: number, } | { "type": "terminated", 
/**
 * Member name
 */
name: string, } | { "type": "failed", 
/**
 * Member name
 */
name: string, 
/**
 * Error description
 */
error: string, } | { "type": "load_started", 
/**
 * Composable node name
 */
name: string, } | { "type": "load_succeeded", 
/**
 * Composable node name
 */
name: string, 
/**
 * Full ROS node name
 */
full_node_name: string, 
/**
 * Unique ID from LoadNode response
 */
unique_id: number, } | { "type": "load_failed", 
/**
 * Composable node name
 */
name: string, 
/**
 * Error message
 */
error: string, } | { "type": "unloaded", 
/**
 * Composable node name
 */
name: string, } | { "type": "blocked", 
/**
 * Composable node name
 */
name: string, 
/**
 * Reason for blocking
 */
reason: BlockReason, };
