// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of SystemStats fields for SSE streaming.
 *
 * Exported to TypeScript like every other type crossing the web boundary:
 * `store.js` referenced `types.SystemStatsSnapshot`, which did not exist,
 * so the frontend's view of this payload was unchecked.
 */
export type SystemStatsSnapshot = { cpu_percent: number, cpu_count: number, memory_used_bytes: number, memory_total_bytes: number, network_rx_rate_bps: number | null, network_tx_rate_bps: number | null, disk_read_rate_bps: number | null, disk_write_rate_bps: number | null, gpu_utilization_percent: number | null, gpu_memory_used_bytes: number | null, gpu_memory_total_bytes: number | null, };
