// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposableNodeStatus } from "./ComposableNodeStatus";
import type { NodeStatus } from "./NodeStatus";

/**
 * Unified status for all node types
 */
export type UnifiedStatus = { "type": "Process", "value": NodeStatus } | { "type": "Composable", "value": ComposableNodeStatus };
