#!/usr/bin/env python3
"""
Compare two record.json files for semantic equivalence.
Part of Phase 13: Rust Parser Migration

This script normalizes and compares record.json files generated by
Rust and Python parsers, accounting for differences in ordering,
formatting, and type representation.
"""

import json
import sys
from typing import Any, Dict, List, Tuple
from pathlib import Path


def normalize_value(value: Any) -> Any:
    """Normalize values for comparison (handle type differences)"""
    # Convert numeric strings to numbers for comparison
    if isinstance(value, str):
        # Try to parse as number
        try:
            if '.' in value:
                return float(value)
            else:
                return int(value)
        except ValueError:
            pass

    # Recursively normalize lists and dicts
    if isinstance(value, list):
        return [normalize_value(v) for v in value]
    elif isinstance(value, dict):
        return {k: normalize_value(v) for k, v in value.items()}

    return value


def normalize_params(params: List[List[str]]) -> List[Tuple[str, Any]]:
    """Normalize parameter list for comparison"""
    if not params:
        return []

    normalized = []
    for param in params:
        if len(param) == 2:
            key, value = param
            normalized.append((key, normalize_value(value)))
        else:
            # Handle unexpected format
            normalized.append(tuple(param))

    # Sort by key for consistent ordering
    return sorted(normalized, key=lambda x: x[0])


def normalize_node(node: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize node record for comparison"""
    normalized = {}

    # Copy all fields
    for key, value in node.items():
        if key == 'params' and value:
            normalized[key] = normalize_params(value)
        elif key == 'params_files' and value:
            # Sort for consistent ordering
            normalized[key] = sorted(value)
        elif key == 'remaps' and value:
            # Sort remaps
            normalized[key] = sorted(value)
        elif key == 'env' and value:
            # Sort environment variables
            normalized[key] = sorted(value.items()) if isinstance(value, dict) else value
        elif value is None:
            # Keep None values for comparison
            normalized[key] = None
        else:
            normalized[key] = value

    return normalized


def normalize_load_node(load_node: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize composable node record for comparison"""
    normalized = {}

    for key, value in load_node.items():
        if key == 'params' and value:
            normalized[key] = normalize_params(value)
        elif key == 'remaps' and value:
            normalized[key] = sorted(value)
        elif key == 'extra_args' and value:
            # Normalize extra_args dict
            normalized[key] = {k: normalize_value(v) for k, v in value.items()}
        elif value is None:
            normalized[key] = None
        else:
            normalized[key] = value

    return normalized


def normalize_record(record: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize entire record for comparison"""
    normalized = {}

    # Normalize nodes
    if 'node' in record:
        nodes = [normalize_node(n) for n in record['node']]
        # Sort by (name, namespace, package) for consistent ordering
        normalized['node'] = sorted(
            nodes,
            key=lambda n: (
                n.get('name', ''),
                n.get('namespace', ''),
                n.get('package', ''),
                n.get('executable', '')
            )
        )
    else:
        normalized['node'] = []

    # Normalize composable nodes
    if 'load_node' in record:
        load_nodes = [normalize_load_node(ln) for ln in record['load_node']]
        # Sort by (node_name, target_container_name)
        normalized['load_node'] = sorted(
            load_nodes,
            key=lambda ln: (
                ln.get('node_name', ''),
                ln.get('target_container_name', ''),
                ln.get('plugin', '')
            )
        )
    else:
        normalized['load_node'] = []

    # Normalize containers
    if 'container' in record:
        containers = record['container']
        # Sort by (name, namespace)
        normalized['container'] = sorted(
            containers,
            key=lambda c: (c.get('name', ''), c.get('namespace', ''))
        )
    else:
        normalized['container'] = []

    # Lifecycle nodes (simple string list)
    if 'lifecycle_node' in record:
        normalized['lifecycle_node'] = sorted(record['lifecycle_node'])
    else:
        normalized['lifecycle_node'] = []

    # File data (parameter files)
    if 'file_data' in record:
        # File data should be identical (content-addressed)
        normalized['file_data'] = record['file_data']
    else:
        normalized['file_data'] = {}

    return normalized


def print_diff_summary(rust_record: Dict, python_record: Dict) -> None:
    """Print a summary of differences between records"""
    print("\n  Difference Summary:")
    print("  " + "=" * 60)

    # Compare counts
    for key in ['node', 'load_node', 'container', 'lifecycle_node']:
        rust_count = len(rust_record.get(key, []))
        python_count = len(python_record.get(key, []))
        if rust_count != python_count:
            print(f"  {key} count: Rust={rust_count}, Python={python_count}")

    # Compare file_data
    rust_files = set(rust_record.get('file_data', {}).keys())
    python_files = set(python_record.get('file_data', {}).keys())
    if rust_files != python_files:
        print(f"  file_data: Rust has {len(rust_files)} files, Python has {len(python_files)} files")
        if rust_files - python_files:
            print(f"    Rust-only files: {rust_files - python_files}")
        if python_files - rust_files:
            print(f"    Python-only files: {python_files - rust_files}")

    # Detailed node comparison
    if rust_record.get('node') != python_record.get('node'):
        print("\n  Node differences detected:")
        for i, (r_node, p_node) in enumerate(zip(
            rust_record.get('node', []),
            python_record.get('node', [])
        )):
            if r_node != p_node:
                print(f"\n    Node {i}:")
                print(f"      Rust:   {r_node.get('name', 'N/A')} ({r_node.get('package', 'N/A')})")
                print(f"      Python: {p_node.get('name', 'N/A')} ({p_node.get('package', 'N/A')})")

                # Show specific field differences
                all_keys = set(r_node.keys()) | set(p_node.keys())
                for key in sorted(all_keys):
                    r_val = r_node.get(key)
                    p_val = p_node.get(key)
                    if r_val != p_val:
                        print(f"        {key}:")
                        print(f"          Rust:   {r_val}")
                        print(f"          Python: {p_val}")

    print("  " + "=" * 60)


def compare_records(rust_path: str, python_path: str, verbose: bool = True) -> bool:
    """
    Compare two record.json files for semantic equivalence.

    Returns True if records are equivalent, False otherwise.
    """
    # Load files
    try:
        with open(rust_path, 'r') as f:
            rust_record = json.load(f)
    except Exception as e:
        print(f"Error loading Rust record from {rust_path}: {e}")
        return False

    try:
        with open(python_path, 'r') as f:
            python_record = json.load(f)
    except Exception as e:
        print(f"Error loading Python record from {python_path}: {e}")
        return False

    # Normalize both records
    rust_norm = normalize_record(rust_record)
    python_norm = normalize_record(python_record)

    # Compare
    if rust_norm == python_norm:
        if verbose:
            print("  ✓ Records are semantically equivalent")
        return True
    else:
        if verbose:
            print("  ✗ Records differ")
            print_diff_summary(rust_norm, python_norm)
        return False


def main():
    """Main entry point"""
    if len(sys.argv) < 3:
        print("Usage: compare_records.py <rust_record.json> <python_record.json>")
        print("\nCompares two record.json files for semantic equivalence.")
        print("Accounts for differences in ordering, formatting, and type representation.")
        sys.exit(1)

    rust_path = sys.argv[1]
    python_path = sys.argv[2]

    # Check files exist
    if not Path(rust_path).exists():
        print(f"Error: {rust_path} not found")
        sys.exit(1)

    if not Path(python_path).exists():
        print(f"Error: {python_path} not found")
        sys.exit(1)

    # Compare
    success = compare_records(rust_path, python_path, verbose=True)

    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
